# Recent projects and publications using BC Cancer Registry data

Annually, BC Cancer receives a significant number of applications from researchers from a variety of health research disciplines to use data from the BC Cancer Registry. Active projects are listed below to demonstrate the diversity of studies that make use of Cancer Registry data each year. The name of the principle applicant for the study is listed along with the study title. The applications may come to BC Cancer directly or facilitated through other research platforms that include BC Cancer Registry data such as Population Data BC.

## Recent projects initiated with BC Cancer Registry data

**Impact of 21-gene recurrence score assay on adjuvant systemic therapy selection in early-stage breast cancer: is cost-effectiveness age-dependent?**

*Principle investigator: Caroline Lohrisch*

**Developing a Framework for the Incorporation of Real World Evidence into Cancer Drug Funding**			

*Principle investigator: Stuart Peacock*

**Examining the epidemiology, treatment, and survival in young-onset colorectal cancer (EXPLAIN-yCRC)**			

*Principle investigator: Mary De Vera*

**Surgical Outcomes for GEP-NETs in British Columbia: A Retrospective Review**			

*Principle investigator: Jonathan Loree*

**Spatial Epidemiological Analysis of Cancer Incidence at a Small Geographic Area Level in British Columbia and Yukon.**			

*Principle investigator: Gina Ogilvie*

**Locoregional Recurrence in Breast Cancer: Outcomes and Prognostic Factors**			

*Principle investigator: Sarah Taylor*

**Socio-demographic Characteristics of Women with Cervical Cancer in British Columbia: 2004-2018**			

*Principle investigator: Gina Ogilvie*

<!-- **First Nations Cancer Research & Surveillance Project**			 -->

<!-- *Principle investigator: Ryan Woods* -->

**The impact of patient choice on patient reported outcomes following mastectomy**			

*Principle investigator: Chris Baliski*

**Examining the frequency of radiographic tumor response assessment in the real world for patients receiving palliative first line chemotherapy for breast, colorectal, lung cancer**			

*Principle investigator: Cheryl Ho*

**Patients with brain metastases in British Columbia: Comparing patterns of care and outcomes between 2012 and 2016.**			

*Principle investigator: Alan Nichol*

**Mesothelioma epidemiology and prognosis**			

*Principle investigator: Chris McLeod*

**Understanding the impact of relapsed lymphoid cancers**			

*Principle investigator: Dean Regier*

**Review of clinical outcome of post-operative intraperitoneal chemotherapy for patients with high grade serous ovarian cancer (HBSC) treated at BC Cancer Agency**			

*Principle investigator: Anna Tinker*

**Incidence and significance of inflammatory bowel disease found at screening colonoscopy**			

*Principle investigator: Jennifer Telford*

**International multiple myeloma consortium pooled data and samples analyses**			

*Principle investigator: John Spinelli*

**The Determinants of Brachytherapy Utilization for Locally-advanced Cervical Cancer in British Columbia. A Population-based Study**			

*Principle investigator: Hamid Raziee*

**Cost-effectiveness of prostate cancer screening in British Columbia**			

*Principle investigator: Adam Raymakers*

**Use of next generation sequencing to identify biomarkers in colorectal cancer**			

*Principle investigator: Jonathan Loree*

**Platin in patients with metastatic castration resistant prostate cancer**			

*Principle investigator: Kim Chi*

**Management of Non-Small Cell Lung Cancer in British Columbia - a 10-Year Analysis of the BC Cancer Population**			

*Principle investigator: Andra Krauze*

**Assessing variations in radiotherapy utilization and shortfalls across Canada**			

*Principle investigator: Michael Brundage*

**Descriptive Epidemiology of Primary Brain Tumours**			

*Principle investigator: Ryan Woods*

**Automated retrospective review of the effects of supportive cancer care interventions on quality of life and survival at BC Cancer**			

*Principle investigator: Alan Bates*

**Maternal and child outcomes after pregnancy-associated and postpartum cancer**			

*Principle investigator: Amy Metcalfe*

**Deep learning applications in oncology for CT scan segmentation**			

*Principle investigator: Rasika Rajapakshe*

**Developing new palliative care quality indicators and benchmarks in cancer across Canada**			

*Principle investigator: Kimberlyn McGrail*

**ASCENDE-RT Reanalysis: What is the cost and health care burden of PSA failure?**			

*Principle investigator: Scott Tyldesley*

**Economics of precision oncology for metastatic cancers**			

*Principle investigator: Dean Regier*

**Evaluation of the BC HPV Vaccination program by data linkage of the vaccine registry and the BC Cervical Cancer Screening Program.**			

*Principle investigator: Dirk Van Niekerk*

## Recent publications using BC Cancer Registry data

Naik H, Leung B, Laskin J, McDonald M, Srikanthan A, Wu J, et al. Emotional distress and psychosocial needs in patients with breast cancer in British Columbia: younger versus older adults. Breast Cancer Res Treat. 2020;179(2):471–7. 

Ritonja J, McIsaac MA, Sanders E, Kyba CCM, Grundy A, Cordina-Duverger E, et al. Outdoor light at night at residences and breast cancer risk in Canada. Eur J Epidemiol. 2020;1–11. 

Liu SL, Tinker A V. Omission of adjuvant therapy in stage I clear cell ovarian cancer: Review of the BC Cancer experience. Gynecol Oncol Reports. 2020;31. 

Liu SL, Tinker A V. Omission of adjuvant therapy in stage I clear cell ovarian cancer: Review of the BC Cancer experience. Gynecol Oncol Reports [Internet]. 2020 Feb;31:100533. Available from: https://linkinghub.elsevier.com/retrieve/pii/S2352578919301225

Yezefski TA, Le D, Chen L, Speers CH, Chennupati S, Snider J, et al. Comparison of Treatment, Cost, and Survival in Patients With Metastatic Colorectal Cancer in Western Washington, United States, and British Columbia, Canada. JCO Oncol Pract [Internet]. 2020 May;16(5):e425–32. Available from: https://ascopubs.org/doi/10.1200/JOP.19.00719

Smrke A, Leung B, Srikanthan A, McDonald M, Bates A, Ho C. Distinct Features of Psychosocial Distress of Adolescents and Young Adults with Cancer Compared to Adults at Diagnosis: Patient-Reported Domains of Concern. J Adolesc Young Adult Oncol [Internet]. 2020 Aug 1;9(4):540–5. Available from: https://www.liebertpub.com/doi/10.1089/jayao.2019.0157

Chan B, Cameron D, Shokoohi A, Regier D, Lim HJ, Ho C. Readiness of health care systems to generate RWE: Frequency of radiographic imaging of metastatic disease during first-line systemic therapy. J Clin Oncol [Internet]. 2020 Oct 10;38(29_suppl):268–268. Available from: https://ascopubs.org/doi/10.1200/JCO.2020.38.29_suppl.268

Naik H, Leung B, Laskin J, McDonald M, Srikanthan A, Wu J, et al. Emotional distress and psychosocial needs in patients with breast cancer in British Columbia: younger versus older adults. Breast Cancer Res Treat [Internet]. 2020 Jan 19;179(2):471–7. Available from: http://link.springer.com/10.1007/s10549-019-05468-6

Lalani N, Voduc KD, Jimenez RB, Levasseur N, Gondara L, Speers C, et al. Breast Cancer Molecular Subtype as a Predictor of Radiation Therapy Fractionation Sensitivity. Int J Radiat Oncol [Internet]. 2020 Aug; Available from: https://linkinghub.elsevier.com/retrieve/pii/S036030162034133X

Smrke A, Hamm J, Karvat A, Simmons C, Srikanthan A. A retrospective review of 145 patients with angiosarcoma: Radiation therapy, extent of resection and chemotherapy are important predictors of survival. Mol Clin Oncol [Internet]. 2020 Jun 2;13(2):179–85. Available from: http://www.spandidos-publications.com/10.3892/mco.2020.2055

Deruchie A, Willemsma K, MacNeill A, DeVries K, Srikanthan A, McGahan C, et al. Tyrosine kinase inhibitors significantly improved survival outcomes in patients with metastatic gastrointestinal stromal tumour: a multi-institutional cohort study. Curr Oncol [Internet]. 2020 Feb 18;27(3). Available from: https://current-oncology.com/index.php/oncology/article/view/5869

Winget M, Yuan Y, McBride ML, Kendell C, Decker KM, Grunfeld E, et al. Inter- and intra-provincial variation in screen-detected breast cancer across five Canadian provinces: a CanIMPACT study. Can J Public Heal [Internet]. 2020 Oct 4;111(5):794–803. Available from: http://link.springer.com/10.17269/s41997-019-00282-5

Warner FM, Darvishian M, Boyle T, Brooks-Wilson AR, Connors JM, Lai AS, et al. Tattoos and Hematologic Malignancies in British Columbia, Canada. Cancer Epidemiol Biomarkers Prev [Internet]. 2020 Oct;29(10):2093–5. Available from: http://cebp.aacrjournals.org/lookup/doi/10.1158/1055-9965.EPI-20-0515

Wang G, Zhou C, Villamil CF, So A, Yuan R, English JC, et al. Metastatic Renal Cell Carcinoma to the Testis: A Clinicopathologic Analysis of Five Cases. Case Rep Pathol [Internet]. 2020 Mar 4;2020:1–6. Available from: https://www.hindawi.com/journals/cripa/2020/9394680/

Sunderland AJ, Steiner RE, Al Zahrani M, Pinnix CC, Dabaja BS, Gunther JR, et al. An international multicenter retrospective analysis of patients with extranodal marginal zone lymphoma and histologically confirmed central nervous system and dural involvement. Cancer Med [Internet]. 2020 Jan 5;9(2):663–70. Available from: https://onlinelibrary.wiley.com/doi/10.1002/cam4.2732

Dhalla A, McDonald TE, Gallagher RP, Spinelli JJ, Brooks-Wilson AR, Lee TK, et al. Cohort Profile: The British Columbia Generations Project (BCGP). Int J Epidemiol. 2019 Apr 1;48(2):377-378k. 

Roy S, Sia M, Tyldesley S, Bahl G. Pathologically Node-Positive Prostate Carcinoma – Prevalence, Pattern of Care and Outcome From a Population-Based Study. Clin Oncol. 2019;31(2):91–8. 

Powis M, Groome P, Biswanger N, Kendell C, Decker KM, Grunfeld E, et al. Cross-Canada differences in early-stage breast cancer treatment and acute-care use. Curr Oncol. 2019;26(5):e624–39. 

García HAV, Gotay CC, Wilson CM, Lohrisch CA, Lai AS, Aronson KJ, et al. Mammographic density parameters and breast cancer tumor characteristics among postmenopausal women. Breast Cancer Targets Ther. 2019;11:261–71. 

Ng HS, Vitry A, Koczwara B, Roder D, McBride ML. Patterns of comorbidities in women with breast cancer: a Canadian population-based study. Cancer Causes Control. 2019;30(9):931–41. 

Li D, Hu XJ, McBride ML, Spinelli JJ. Multiple event times in the presence of informative censoring: modeling and analysis by copulas. Lifetime Data Anal. 2019;1–30. 

Lofters AK, McBride ML, Li D, Whitehead M, Moineddin R, Jiang L, et al. Disparities in breast cancer diagnosis for immigrant women in Ontario and BC: Results from the CanIMPACT study. BMC Cancer. 2019;19(1):1–11. 

Hanley GE, McAlpine JN, Cheifetz R, Schrader KA, McCullum M, Huntsman D. Selected medical interventions in women with a deleterious BRCA mutation: A population-based study in British Columbia. Curr Oncol. 2019;26(1):e17–23. 

Hamilton SN, Arshad O, Kwok J, Tran E, Fuchsia Howard A, Serrano I, et al. Documentation and incidence of late effects and screening recommendations for adolescent and young adult head and neck cancer survivors treated with radiotherapy. Support Care Cancer. 2019;27(7):2609–16. 

Costa S, Scott DW, Steidl C, Peacock SJ, Regier DA. Real-world costing analysis for diffuse large b-cell lymphoma in British Columbia. Curr Oncol. 2019;26(2):108–13. 

Lee DG, Burstyn I, Lai AS, Grundy A, Friesen MC, Aronson KJ, et al. Women’s occupational exposure to polycyclic aromatic hydrocarbons and risk of breast cancer. Occup Environ Med. 2019;76(1):22–9. 

Moosavi S, Gentile L, Gondara L, Mcgahan C, Enns RA, Telford J. Performance of the Fecal Immunochemical Test in Patients With a Family History of Colorectal Cancer. J Can Assoc Gastroenterol. 2019; 

Al-Hashami ZS, Ho C, Moore S, Leung B, Lim HJ, Bates A. The impact of psychosocial distress on survival in patients diagnosed with gastrointestinal (GI) malignancies. J Clin Oncol. 2019;37(4_suppl):654–654. 

Schuetz JM, Grundy A, Lee DG, Lai AS, Kobayashi LC, Richardson H, et al. Genetic variants in genes related to inflammation, apoptosis and autophagy in breast cancer risk. PLoS One. 2019;14(1). 

Mar C, Sam J, McGahan CE, DeVries K, Coldman A. The influence of breast density on breast cancer diagnosis: A study of participants in the BC Cancer breast screening program. BC Med J. 2019;61(10):376–84. 

Vanderveer E, Huang SJT, Bruyere H, Gillan T, Li CH, Ramadan K, et al. Oral Fludarabine and Intravenous Rituximab (FR) for Chronic Lymphocytic Leukemia (CLL): Long Term Outcomes and Secondary Malignancies in 673 Patients Treated in British Columbia (BC). Blood. 2019;134(Supplement_1):4300–4300. 

Liu SL, Yu IS, Lau SC, Zhao Y, Schellenberg D, Gill S, et al. Perioperative chemotherapy alone versus preoperative chemoradiotherapy for locally advanced distal esophageal and gastroesophageal junction cancer: A 10-year review of the British Columbia (BC) Cancer Registry. J Clin Oncol. 2019;37(15_suppl):4028–4028. 

Darvishian M, Wong S, Binka M, Yu A, Ramji A, Yoshida EM, et al. Loss to follow-up: A significant barrier in the treatment cascade with direct-acting therapies. J Viral Hepat. 2019;27(3):243–60. 

Angeles A, Hung W, Cheung WY. Eligibility of real-world patients with chemo-refractory, K-RAS wild-type, metastatic colorectal cancer for palliative intent regorafenib monotherapy. Med Oncol. 2018;35(8):1–7. 

Darvishian M, Janjua NZ, Chong M, Cook D, Samji H, Butt ZA, et al. Estimating the impact of early hepatitis C virus clearance on hepatocellular carcinoma risk. J Viral Hepat. 2018;25(12):1481–92. 

Butt ZA, Shrestha N, Gesink D, Murti M, Buxton JA, Gilbert M, et al. Effect of opioid-substitution therapy and mental health counseling on hiv risk among hepatitis c-infected individuals. Clin Epidemiol. 2018;10:1127–45. 

Lefresne S, Cheung WY, Hay J, Brown CJ, Speers C, Olson R. Management of stage II and III rectal cancer in British Columbia: Is there a rural-urban difference? Am J Surg. 2018;216(5):906–11. 

Teckle P, Peacock S, McBride ML, Bentley C, Goddard K, Rogers P. Long-term effects of cancer on earnings of childhood, adolescent and young adult cancer survivors - A population-based study from British Columbia, Canada 11 Medical and Health Sciences 1117 Public Health and Health Services. BMC Health Serv Res. 2018;18(1):1–10. 

Tseng OL, Spinelli JJ, Gotay CC, Ho WY, McBride ML, Dawes MG. Promoting bone health management in women diagnosed with breast cancer: a pilot randomized controlled trial. Arch Osteoporos. 2018;13(1):1–9. 

Velásquez García HA, Sobolev BG, Gotay CC, Wilson CM, Lohrisch CA, Lai AS, et al. Mammographic non-dense area and breast cancer risk in postmenopausal women: a causal inference approach in a case–control study. Breast Cancer Res Treat. 2018;170(1):159–68. 

Canale TD, Cho HK, Cheung WY. A population-based analysis of urban–rural disparities in advanced pancreatic cancer management and outcomes. Med Oncol. 2018;35(8):1–8. 

Weber L, Song K, Boyle T, Gaudreau É, Lai A, Sutherland HJ, et al. Organochlorine levels in plasma and risk of multiple myeloma. J Occup Environ Med. 2018;60(10):911–6. 

Hanley GE, McAlpine JN, Miller D, Huntsman D, Schrader KA, Blake Gilks C, et al. A population-based analysis of germline BRCA1 and BRCA2 testing among ovarian cancer patients in an era of histotype-specific approaches to ovarian cancer prevention. BMC Cancer [Internet]. 2018;18(1):254. Available from: https://bmccancer.biomedcentral.com/articles/10.1186/s12885-018-4153-8

Stubbins RJ, Lee L, Abou Mourad Y, Barnett MJ, Broady R, Forrest DL, et al. Older Adults with Acute Myeloid Leukemia in Rural Areas Are Less Likely to Receive Azacitidine with Worsened Overall Survival. Blood. 2018;132(Supplement 1):3989–3989. 

Woods RR, McGrail KM, Kliewer E V., Kazanjian A, Mar C, Kan L, et al. Breast screening participation and retention among immigrants and nonimmigrants in British Columbia: A population-based study. Cancer Med. 2018;7(8):4044–67. 

Lu XJD, Liu KYP, Soares RC, Thomson T, Prisman E, Wu J, et al. Potential clinical implications of HPV status and expressions of p53 and cyclin D1 among oropharyngeal cancer patients. J Oral Pathol Med. 2018;47(10):945–53. 

Arora N, Talhouk A, McAlpine JN, Law MR, Hanley GE. Long-term mortality among women with epithelial ovarian cancer: A population-based study in British Columbia, Canada. BMC Cancer. 2018;18(1):1–9. 

Pataky R, Tran DA, Coronado A, Alvi R, Boehm D, Regier DA, et al. Cancer drug expenditure in British Columbia and Saskatchewan: a trend analysis. C Open. 2018;6(3):E292–9. 
